#!/bin/sh

# You may find this shell script helpful.

export PATH=/usr/pubsw/bin:$PATH

java -server -Xmx3000m -cp classes \
  cs224n.assignments.DecoderTester \
  -lmmodel     cs224n.langmodel.EmpiricalUnigramLanguageModel \
  -wamodel     cs224n.wordaligner.ModelOneWordAligner \
  -lmsentences 1000 \
  -wasentences 500 \
  $@

java modelone > outfile 2>&1  
